name: Feature request / 功能建議
description: Suggest an idea / 提出新想法
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like? / 你希望有什麼功能？
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why? What problem does it solve? / 想解決什麼問題？
